-- MÃO NA BRASA - ESTRUTURA COMPLETA DO SUPABASE
-- Execute este arquivo inteiro no SQL Editor do projeto hpjvlayhinbtpgmlocaw.

create table if not exists public.mnb_admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.mnb_products (
  id text primary key,
  name text not null,
  category text not null default 'Outros',
  tag text not null default '',
  description text not null default '',
  price numeric(10,2) not null default 0 check (price >= 0),
  image text not null default '',
  image_fit text not null default 'cover',
  image_position text not null default 'center',
  has_addons boolean not null default false,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mnb_addons (
  id text primary key,
  name text not null unique,
  price numeric(10,2) not null default 0 check (price >= 0),
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.mnb_orders (
  id bigint generated by default as identity primary key,
  protocol text not null unique,
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'enviado_whatsapp',
  created_at timestamptz not null default now()
);

create table if not exists public.mnb_site_settings (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.mnb_admin_profiles enable row level security;
alter table public.mnb_products enable row level security;
alter table public.mnb_addons enable row level security;
alter table public.mnb_orders enable row level security;
alter table public.mnb_site_settings enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.mnb_products, public.mnb_addons, public.mnb_site_settings to anon, authenticated;
grant insert on public.mnb_orders to anon, authenticated;
grant select, insert, update, delete on public.mnb_products, public.mnb_addons, public.mnb_orders, public.mnb_site_settings to authenticated;
grant select on public.mnb_admin_profiles to authenticated;
grant usage, select on sequence public.mnb_orders_id_seq to anon, authenticated;

drop policy if exists "Produtos públicos disponíveis" on public.mnb_products;
create policy "Produtos públicos disponíveis" on public.mnb_products for select to anon
using (available = true);
drop policy if exists "Produtos visíveis para usuários" on public.mnb_products;
create policy "Produtos visíveis para usuários" on public.mnb_products for select to authenticated
using (available = true or exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));
drop policy if exists "Admin gerencia produtos" on public.mnb_products;
create policy "Admin gerencia produtos" on public.mnb_products for all to authenticated
using (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));

drop policy if exists "Adicionais públicos disponíveis" on public.mnb_addons;
create policy "Adicionais públicos disponíveis" on public.mnb_addons for select to anon
using (available = true);
drop policy if exists "Adicionais visíveis para usuários" on public.mnb_addons;
create policy "Adicionais visíveis para usuários" on public.mnb_addons for select to authenticated
using (available = true or exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));
drop policy if exists "Admin gerencia adicionais" on public.mnb_addons;
create policy "Admin gerencia adicionais" on public.mnb_addons for all to authenticated
using (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));

drop policy if exists "Cliente registra pedido" on public.mnb_orders;
create policy "Cliente registra pedido" on public.mnb_orders for insert to anon, authenticated
with check (total >= 0 and jsonb_array_length(items) > 0);
drop policy if exists "Admin consulta pedidos" on public.mnb_orders;
create policy "Admin consulta pedidos" on public.mnb_orders for select to authenticated
using (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));
drop policy if exists "Admin atualiza pedidos" on public.mnb_orders;
create policy "Admin atualiza pedidos" on public.mnb_orders for update to authenticated
using (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));

drop policy if exists "Configuração pública" on public.mnb_site_settings;
create policy "Configuração pública" on public.mnb_site_settings for select to anon, authenticated using (true);
drop policy if exists "Admin gerencia configuração" on public.mnb_site_settings;
create policy "Admin gerencia configuração" on public.mnb_site_settings for all to authenticated
using (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));

drop policy if exists "Admin consulta próprio perfil" on public.mnb_admin_profiles;
create policy "Admin consulta próprio perfil" on public.mnb_admin_profiles for select to authenticated
using (user_id = (select auth.uid()));

insert into public.mnb_site_settings (id, settings) values
('main', '{"businessName":"Mao na Brasa","whatsappNumber":"556492360895","deliveryFee":10,"brandLabel":"Mao na Brasa"}'::jsonb)
on conflict (id) do nothing;

insert into public.mnb_addons (id, name, price, available, sort_order) values
('carne-extra','Carne Extra',7.90,true,1),
('bacon-extra','Bacon Extra',5.90,true,2),
('queijo-extra','Queijo Extra',3.90,true,3),
('salada-extra','Salada Extra',0.90,true,4),
('cebola-extra','Cebola Extra',0.90,true,5),
('molho-extra','Molho Extra',0.90,true,6),
('queijo-empanado','Queijo Empanado',8.90,true,7),
('frango-empanado','Frango Empanado',9.90,true,8),
('queijo-cheddar','Queijo Cheddar',5.90,true,9),
('molho-cheddar','Molho Cheddar',7.90,true,10)
on conflict (id) do update set name=excluded.name, price=excluded.price,
available=excluded.available, sort_order=excluded.sort_order;

insert into storage.buckets (id, name, public)
values ('mnb-images', 'mnb-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Imagens públicas MNB" on storage.objects;
create policy "Imagens públicas MNB" on storage.objects for select to anon, authenticated
using (bucket_id = 'mnb-images');
drop policy if exists "Admin envia imagens MNB" on storage.objects;
create policy "Admin envia imagens MNB" on storage.objects for insert to authenticated
with check (bucket_id = 'mnb-images' and exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));
drop policy if exists "Admin atualiza imagens MNB" on storage.objects;
create policy "Admin atualiza imagens MNB" on storage.objects for update to authenticated
using (bucket_id = 'mnb-images' and exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())))
with check (bucket_id = 'mnb-images' and exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));
drop policy if exists "Admin exclui imagens MNB" on storage.objects;
create policy "Admin exclui imagens MNB" on storage.objects for delete to authenticated
using (bucket_id = 'mnb-images' and exists (select 1 from public.mnb_admin_profiles a where a.user_id = (select auth.uid())));

-- Libera como administrador o usuário já criado com este e-mail.
insert into public.mnb_admin_profiles (user_id, email)
select id, email from auth.users where lower(email) = lower('williancarlos0103@gmail.com')
on conflict (user_id) do update set email = excluded.email;

-- Se o usuário for criado depois, execute novamente apenas o bloco acima.
